version: '3'

services:
  proxy:
    image: nginx:latest
    container_name: skyst_proxy
    ports:
      - "${PORT:?err}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  db:
    image: mysql:8.0
    container_name: skyst_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?err}
      - MYSQL_DATABASE=${MYSQL_DATABASE:?err}
      - MYSQL_USER=${MYSQL_USER:?err}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?err}

  server:
    build: .
    container_name: skyst_server
    depends_on:
      - db
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE:?err}
    - MYSQL_USER=${MYSQL_USER:?err}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD:?err}
    - MYSQL_HOST=skyst_db
    command: ["python3", "app.py"]
  
  socket:
    build: .
    container_name: skyst_socket
    depends_on:
      - db
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE:?err}
    - MYSQL_USER=${MYSQL_USER:?err}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD:?err}
    - MYSQL_HOST=skyst_db
    command: ["python3", "app_message.py"]