version: '3'

services:
  db:
    image: mysql:8.0
    container_name: skyst_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?err}
      - MYSQL_DATABASE=${MYSQL_DATABASE:?err}
      - MYSQL_USER=${MYSQL_USER:?err}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?err}
  server:
    build: .
    container_name: skyst_server
    depends_on:
      - db
    ports:
      - "${PORT}:5000"
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE:?err}
    - MYSQL_USER=${MYSQL_USER:?err}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD:?err}
    - MYSQL_HOST=db
    